"""公共模块 — Common Utilities Layer

提供项目中各模块共用的基础设施。

整合了以下功能:
- exceptions: 层次化异常类 (配置/数据/分析/索引/LLM/依赖)
- logging: 基于 loguru 的统一日志系统 (支持结构化日志和性能计时)
- utils: 常用工具函数 (字符串/文件/哈希/数值/时间/批处理)
"""

from .exceptions import (
    CoreLinuxCommitError,
    ConfigurationError,
    MissingConfigError,
    InvalidConfigError,
    DataError,
    ParsingError,
    InvalidDataFormat,
    AnalysisError,
    DmesgParsingError,
    VmcoreAnalysisError,
    RootCauseAnalysisError,
    IndexingError,
    EmbeddingError,
    VectorDBError,
    RetrievalError,
    LLMError,
    LLMUnavailableError,
    LLMResponseError,
    DependencyError,
    GitRepoError,
    DrgnError,
    ModelNotAvailableError,
)
from .logging import (
    setup_logging,
    get_logger,
    reset_logger,
    log_time,
    timed,
    log_event,
    log_error_with_context,
    LogLevel,
)
from .utils import (
    truncate_text,
    clean_text,
    extract_commit_hash,
    extract_cve_ids,
    extract_email,
    ensure_dir,
    safe_filename,
    get_file_size_mb,
    hash_text,
    short_hash,
    generate_id,
    safe_divide,
    sigmoid,
    normalize_scores,
    softmax,
    format_duration,
    parse_kernel_version,
    compare_kernel_versions,
    batch_iterate,
    chunk_list,
    flatten_dict,
    safe_json_loads,
    to_bool,
    get_call_info,
    memory_usage_mb,
    profile,
    memoize,
)

__all__ = [
    # 异常
    "CoreLinuxCommitError",
    "ConfigurationError",
    "MissingConfigError",
    "InvalidConfigError",
    "DataError",
    "ParsingError",
    "InvalidDataFormat",
    "AnalysisError",
    "DmesgParsingError",
    "VmcoreAnalysisError",
    "RootCauseAnalysisError",
    "IndexingError",
    "EmbeddingError",
    "VectorDBError",
    "RetrievalError",
    "LLMError",
    "LLMUnavailableError",
    "LLMResponseError",
    "DependencyError",
    "GitRepoError",
    "DrgnError",
    "ModelNotAvailableError",
    # 日志
    "setup_logging",
    "get_logger",
    "reset_logger",
    "log_time",
    "timed",
    "log_event",
    "log_error_with_context",
    "LogLevel",
    # 工具
    "truncate_text",
    "clean_text",
    "extract_commit_hash",
    "extract_cve_ids",
    "extract_email",
    "ensure_dir",
    "safe_filename",
    "get_file_size_mb",
    "hash_text",
    "short_hash",
    "generate_id",
    "safe_divide",
    "sigmoid",
    "normalize_scores",
    "softmax",
    "format_duration",
    "parse_kernel_version",
    "compare_kernel_versions",
    "batch_iterate",
    "chunk_list",
    "flatten_dict",
    "safe_json_loads",
    "to_bool",
    "get_call_info",
    "memory_usage_mb",
    "profile",
    "memoize",
]
